### PR TITLE
KATANA KAMI: A Way of the Samurai Story

### PR DESCRIPTION
**Pull request by cucholix**
KATANA KAMI: A Way of the Samurai Story
ver. 1.0.3
(US version)

### CODE REVIEW

**Comment by masagrator** [comment]
UnityEngine.ScalableBufferManager::ResizeBuffers is really working?

**Comment by masagrator** [comment]
Didn't get an answer for over a year. :P

**Comment by cucholix** [comment]
> UnityEngine.ScalableBufferManager::ResizeBuffers is really working?

For this game no

**Comment by masagrator** [comment]
Then if you want to reopen it, null pointer for ResizeBuffers

**Pull request closed without merging**
